[package]
categories.workspace = true
description = "GKR IOP protocol implementation"
edition.workspace = true
keywords.workspace = true
license.workspace = true
name = "gkr_iop"
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
ark-std = { version = "0.5" }
bincode.workspace = true
clap.workspace = true
either.workspace = true
ff_ext = { path = "../ff_ext" }
itertools.workspace = true
multilinear_extensions = { version = "0.1.0", path = "../multilinear_extensions" }
ndarray.workspace = true
p3.workspace = true
rand.workspace = true
serde.workspace = true
sumcheck.workspace = true
thiserror.workspace = true
tiny-keccak.workspace = true
tracing.workspace = true
tracing-forest.workspace = true
tracing-subscriber.workspace = true
transcript = { path = "../transcript" }
witness = { path = "../witness" }

[target.'cfg(unix)'.dependencies]
tikv-jemalloc-ctl = { version = "0.6", features = ["stats"], optional = true }
tikv-jemallocator = { version = "0.6", optional = true }

[dev-dependencies]
criterion.workspace = true

[[bench]]
harness = false
name = "bitwise_keccakf"

[[bench]]
harness = false
name = "lookup_keccakf"

[features]
jemalloc = ["dep:tikv-jemallocator", "dep:tikv-jemalloc-ctl"]
